package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// The M1 overlay writes into CLAUDE.md between these markers only. Everything
// outside them is the host's and is never touched (augment-never-clobber); a
// re-run replaces what is between them (idempotent).
const (
	trellisBegin = "<!-- trellis:begin (managed — edit .trellis/profile.md, not this block) -->"
	trellisEnd   = "<!-- trellis:end -->"
)

// applyM1 performs the deterministic M1 overlay: write .trellis/profile.md and
// upsert the delimited Trellis block in CLAUDE.md. No model — plain file editing.
func applyM1(dir string, plan Plan) (string, error) {
	if err := os.MkdirAll(filepath.Join(dir, ".trellis"), 0o755); err != nil {
		return "", fmt.Errorf("creating .trellis/: %w", err)
	}
	if err := os.WriteFile(filepath.Join(dir, ".trellis", "profile.md"), []byte(renderProfile(plan)), 0o644); err != nil {
		return "", fmt.Errorf("writing profile: %w", err)
	}

	claudePath := filepath.Join(dir, "CLAUDE.md")
	existing := ""
	if b, err := os.ReadFile(claudePath); err == nil {
		existing = string(b)
	} else if !os.IsNotExist(err) {
		return "", fmt.Errorf("reading CLAUDE.md: %w", err)
	}
	if err := os.WriteFile(claudePath, []byte(upsertBlock(existing, renderClaudeBlock(plan))), 0o644); err != nil {
		return "", fmt.Errorf("writing CLAUDE.md: %w", err)
	}

	return fmt.Sprintf("applied (M1 overlay):\n  wrote %s\n  updated %s (trellis block)\n",
		filepath.Join(".trellis", "profile.md"), "CLAUDE.md"), nil
}

// upsertBlock replaces the delimited trellis block in content if present, else
// appends it. Content outside the markers is preserved exactly.
func upsertBlock(content, block string) string {
	i := strings.Index(content, trellisBegin)
	j := strings.Index(content, trellisEnd)
	if i >= 0 && j > i {
		return content[:i] + block + content[j+len(trellisEnd):]
	}
	if strings.TrimSpace(content) == "" {
		return block + "\n"
	}
	return strings.TrimRight(content, "\n") + "\n\n" + block + "\n"
}

func activeList(plan Plan) string {
	if len(plan.Profile.Active) == 0 {
		return "all assessable invariants"
	}
	return strings.Join(plan.Profile.Active, ", ")
}

func renderClaudeBlock(plan Plan) string {
	return trellisBegin + "\n" +
		"## Trellis governance\n" +
		fmt.Sprintf("This project is supervised by **Trellis** (posture: %s). Active invariants at `%s` enforcement:\n", plan.Profile.Name, plan.Profile.C1Lean) +
		"- " + activeList(plan) + "\n" +
		"**Key behavior:** surface any human-gated handover performed without its human approval (invariant B2). Agent-gated handovers proceed silently.\n" +
		"Gatekeepers are whatever this project already declares — respected, not imposed (decision-0024).\n" +
		"Profile: `.trellis/profile.md`\n" +
		trellisEnd
}

func renderProfile(plan Plan) string {
	return "# Trellis expression profile\n\n" +
		fmt.Sprintf("- posture: %s — %s\n", plan.Profile.Name, plan.Profile.Description) +
		fmt.Sprintf("- enforcement (C1) lean: %s\n", plan.Profile.C1Lean) +
		fmt.Sprintf("- active: %s\n", activeList(plan)) +
		"- gatekeeper (C2): detected from this project, not preset (decision-0024)\n" +
		fmt.Sprintf("- install mode: %s\n", plan.Mode.Name) +
		"\nGenerated by `trellis setup`. Edit this file to tune the profile.\n"
}
