package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// The M1 overlay writes into CLAUDE.md between these markers only. Everything
// outside them is the host's and is never touched (augment-never-clobber); a
// re-run replaces what is between them (idempotent).
const (
	trellisBegin = "<!-- trellis:begin (managed — edit .trellis/profile.md, not this block) -->"
	trellisEnd   = "<!-- trellis:end -->"
)

// applyM1 performs the deterministic M1 overlay: write .trellis/profile.md and
// upsert the delimited Trellis block in CLAUDE.md. No model — plain file editing.
func applyM1(dir string, plan Plan) (string, error) {
	if err := os.MkdirAll(filepath.Join(dir, ".trellis"), 0o755); err != nil {
		return "", fmt.Errorf("creating .trellis/: %w", err)
	}
	if err := os.WriteFile(filepath.Join(dir, ".trellis", "profile.md"), []byte(renderProfile(plan)), 0o644); err != nil {
		return "", fmt.Errorf("writing profile: %w", err)
	}

	claudePath := filepath.Join(dir, "CLAUDE.md")
	existing := ""
	if b, err := os.ReadFile(claudePath); err == nil {
		existing = string(b)
	} else if !os.IsNotExist(err) {
		return "", fmt.Errorf("reading CLAUDE.md: %w", err)
	}
	if err := os.WriteFile(claudePath, []byte(upsertBlock(existing, renderClaudeBlock())), 0o644); err != nil {
		return "", fmt.Errorf("writing CLAUDE.md: %w", err)
	}

	return fmt.Sprintf("applied (M1 overlay):\n  wrote %s\n  updated %s (trellis block)\n",
		filepath.Join(".trellis", "profile.md"), "CLAUDE.md"), nil
}

// upsertBlock replaces the delimited trellis block in content if present, else
// appends it. Content outside the markers is preserved exactly.
func upsertBlock(content, block string) string {
	i := strings.Index(content, trellisBegin)
	j := strings.Index(content, trellisEnd)
	if i >= 0 && j > i {
		return content[:i] + block + content[j+len(trellisEnd):]
	}
	if strings.TrimSpace(content) == "" {
		return block + "\n"
	}
	return strings.TrimRight(content, "\n") + "\n\n" + block + "\n"
}

func activeList(plan Plan) string {
	if len(plan.Profile.Active) == 0 {
		return "all assessable invariants"
	}
	return strings.Join(plan.Profile.Active, ", ")
}

// renderClaudeBlock is the minimal CLAUDE.md footprint: just a native @import of
// the profile between the markers. All the actual content lives in
// .trellis/profile.md (single source — no duplication into the host's file).
func renderClaudeBlock() string {
	return trellisBegin + "\n@.trellis/profile.md\n" + trellisEnd
}

// renderProfile is the single source of truth the @import pulls in: the posture,
// the active invariants, and the governance behavior the agent follows.
func renderProfile(plan Plan) string {
	return "# Trellis expression profile\n\n" +
		fmt.Sprintf("This project is supervised by **Trellis** (posture: %s — %s).\n\n", plan.Profile.Name, plan.Profile.Description) +
		fmt.Sprintf("## Active invariants (enforcement C1: `%s`)\n\n- %s\n\n", plan.Profile.C1Lean, activeList(plan)) +
		"## Key behavior\n\n" +
		"Surface any **human-gated handover performed without its human approval** (invariant B2). Agent-gated handovers proceed silently.\n\n" +
		"Gatekeepers are whatever this project already declares — **respected, not imposed** (decision-0024).\n\n" +
		"## Dials\n\n" +
		"- gatekeeper (C2): detected from this project, not preset (decision-0024)\n" +
		fmt.Sprintf("- install mode: %s\n\n", plan.Mode.Name) +
		"---\nGenerated by `trellis setup`. Edit *this* file to tune the profile; `CLAUDE.md` only imports it.\n"
}
