#!/usr/bin/env bash
# Trellis staleness surface — SessionStart hook (decision-0039).
#
# Surfaces a refresh nudge when a *plugin-generated* .trellis/ overlay is behind the
# currently-installed plugin. Network-free: it compares the overlay's stamped plugin SHA
# (decision-0035/0036) against the installed plugin's HEAD. It can say "how old" (the
# generator differs), not "how far behind" (that would need the marketplace, which the
# no-runtime promise resists — decision-0039 open question). Silent unless there's drift.
#
# Output contract (SessionStart): exit 0; a single-line JSON {"additionalContext": "..."}
# on stdout injects context; empty stdout injects nothing. Never exit non-zero — a hook
# failure must not disrupt the session.

ver="${CLAUDE_PROJECT_DIR:-.}/.trellis/version"
[ -f "$ver" ] || exit 0                          # no overlay here → nothing to say

stamp="$(head -n1 "$ver" 2>/dev/null | tr -d '[:space:]')"
case "$stamp" in
  plugin@unknown | "plugin@" | "")
    exit 0 ;;                                     # unstampable → can't compare → silent
  plugin@*)
    overlay="${stamp#plugin@}"
    current="$(git -C "${CLAUDE_PLUGIN_ROOT:-/nonexistent}" rev-parse --short HEAD 2>/dev/null)" || exit 0
    [ -n "$current" ] || exit 0                   # can't read installed plugin → silent
    if [ "$overlay" != "$current" ]; then
      printf '{"additionalContext": "Trellis overlay may be stale: the .trellis/ overlay in this project was generated by plugin@%s, but the installed Trellis plugin is now plugin@%s. The invariants may have moved on; run /trellis:setup to refresh the overlay."}\n' \
        "$overlay" "$current"
    fi
    ;;
  *)
    exit 0 ;;                                     # a CLI-version stamp → `trellis status` is its surface
esac
exit 0
